baseURL = "bodenlab.github.io/GRASP-suite/"
languageCode = "en-us"
title = "GRASP-suite"
theme = "academia"

publishDir = "docs"

[params]
    name = "GRASP-suite"
    description = "A mystery person"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false
